spring:
  application:
    name: joker-demo-project
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jpa:
    show-sql: false
    database-platform: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        format_sql: false

joker-db:
  jdbc-url: jdbc:postgresql://localhost:5432/joker
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
  testOnBorrow: true
  validationQuery: SELECT 1


server:
  address: 0.0.0.0
  port: 8080

spring.liquibase:
  change-log: classpath:changelog/master.xml


